plugins {
	id 'java'
	id 'org.springframework.boot' version '3.3.3'
	id 'io.spring.dependency-management' version '1.1.6'
}

group = 'org.rest_api.pet'
version = '0.0.1-SNAPSHOT'

java {
	toolchain {
		languageVersion = JavaLanguageVersion.of(21)
	}
}

repositories {
	mavenCentral()
}

dependencies {
	implementation 'org.springframework.boot:spring-boot-starter-actuator'
	implementation 'org.springframework.boot:spring-boot-starter-data-jpa'
	implementation 'org.springframework.boot:spring-boot-starter-validation'
	implementation 'org.springframework.boot:spring-boot-starter-web'
	implementation group: 'org.modelmapper', name: 'modelmapper', version: '3.2.1'
	implementation group: 'org.springdoc', name: 'springdoc-openapi-starter-webmvc-ui', version: '2.0.3'
	implementation 'org.flywaydb:flyway-core'
	implementation 'org.flywaydb:flyway-database-postgresql'

	// JUnit 5
	testImplementation 'org.junit.jupiter:junit-jupiter:5.9.3'

	// Selenium WebDriver
	testImplementation 'org.seleniumhq.selenium:selenium-java:4.14.1'

	// AssertJ для удобных утверждений
	testImplementation 'org.assertj:assertj-core:3.24.2'

	// WebDriver Manager для автоматического управления драйверами браузеров
	testImplementation 'io.github.bonigarcia:webdrivermanager:5.5.3'

	runtimeOnly 'org.postgresql:postgresql'
	testImplementation 'org.springframework.boot:spring-boot-starter-test'
	testRuntimeOnly 'org.junit.platform:junit-platform-launcher'
}

tasks.withType(Test) {
	useJUnitPlatform()
}

tasks.named('test') {
	useJUnitPlatform()
}
